### ISSUE TITLE
[Linux] KDE. Misc missing icons

### ISSUE THREAD

**Issue by jscappini** [NitruxSA/luv-icon-theme#126]
Some lately commons apps have their icons missing:

- GVim [gvim]
- KColorChooser [kcolorchooser]
- KeePassX [keepassx]
- KolourPaint [kolourpaint]
- Kompare [kompare]
- KOrganizer [korganizer]
- KRDC [krdc]
- KSystemLog [ksystemlog]
- Opera developer [opera-developer]
- qBittorrent [qbittorrent]
- Quassel IRC [quassel]
- Robomongo [robomongo]
- Vivaldi (Althought it's kinda flat already) [vivaldi]

![000000000001](https://cloud.githubusercontent.com/assets/1986324/6198186/395df618-b3d4-11e4-8586-b7411cb70f17.png)

Also, could you consider another colour for the folder icon? Just saying. :pray: 

Thanx!

**Comment by UriHerrera** [comment]
You can change the color of the folders using the included script.

**Comment by jscappini** [comment]
My bad! I didn't notice the script. Changes made. Thanx!

**Comment by mueslo** [comment]
Some of the icons missing in KDE are present in the https://github.com/KaOSx/flattr-icons-kde repo. Maybe it could be merged into this repo?

**Comment by UriHerrera** [comment]
@mueslo No, the style is that of the previous Flattr versions and doesn't fit nor in size (in px) or style.
