### ISSUE TITLE
[Linux] Bluetooth icon Mate1.8.1(blueman-applet)

### ISSUE THREAD

**Issue by s-chizhik** [NitruxSA/luv-icon-theme#129]
![Icons](http://www.pixentral.com/pics/1VD4Rabh3lN985KiaEjTkR36MhA5I81.png)
Please add bluetooth icons for two states(on/off).

**Comment by s-chizhik** [comment]
Sorry, forgot to add network-image issues:
wired - ![Icons](http://www.pixentral.com/pics/13Gp8zwDV7lMbeuxqrwbXLbWRz5EIr.png)
wireless(at connect) - ![Icons](http://www.pixentral.com/pics/1w9fEIq6aBYmLVt7CTVJp7Ny4GhmmW0.png)

**Comment by UriHerrera** [comment]
Please open separate issues for the icons. And add the relevant information. https://github.com/NitruxSA/flattr-icons#reporting-missing-icons

**Comment by s-chizhik** [comment]
Done!
