### ISSUE TITLE
Some logos difficult to see at small sizes (~22x22px)

### ISSUE THREAD

**Issue by johnfraney** [NitruxSA/luv-icon-theme#150]
![flattr-atom-icon](https://cloud.githubusercontent.com/assets/1728528/7961799/1ad400f4-09e0-11e5-8291-72196851aa08.png)
![flattr-atom-icon-lightness-50](https://cloud.githubusercontent.com/assets/1728528/7962164/56800272-09e2-11e5-9e2d-8f33cb29d79f.png)
![flattr-atom-icon-white](https://cloud.githubusercontent.com/assets/1728528/7962230/9f7ae6c2-09e2-11e5-8319-a26ceda6ab44.png)

Because of the low contrast between the logo and the background, the Atom icon is difficult to see at smaller sizes. I've attached a comparison with the logo lightness dialed down to 50 (in Inkscape) and another with a white logo.

From a quick glance, I believe that these icons would also be difficult to see at small sizes:
- `amule.svg`
- `system-reboot.svg`
- `soundconverter.svg`

`zen-icon.svg` and `update-manager.svg`, on the other hand, use a darker stroke and are easier to see. I think using that same colour for the Atom icon would do the trick nicely.

**Comment by UriHerrera** [comment]
Yes indeed, this is fixed by having icons for those small sizes.
