### ISSUE TITLE
Guidelines and templates

### ISSUE THREAD

**Issue by EmptyStackExn** [NitruxSA/luv-icon-theme#154]
Hello,
Do you have any guidelines or templates to make icons ? I cannot find them in the actual version of flattr. In particular, it appears they have disappeared since commit `8625e6886b0bd91fd40620b724e0f5b02c8dd8c8`. Do you still stick to the former guideline document ?

Regards,

**Comment by UriHerrera** [comment]
No, I removed the document since the quality of the theme was going down. I'm instead adding new ones to the wiki here on the repo. They're not complete yet however I've only added a couple of pages.
