### ISSUE TITLE
Some symlinks for dark icons aren't relative

### ISSUE THREAD

**Issue by keawade** [NitruxSA/luv-icon-theme#160]
![screenshot from 2016-04-22 00-15-10](https://cloud.githubusercontent.com/assets/7308850/14732680/a970f10a-0822-11e6-8161-96d677cb2f97.png)

**Comment by UriHerrera** [comment]
Yeah it's a KIO bug I'm fixing it.

**Comment by UriHerrera** [comment]
Should be fixed now.

**Comment by keawade** [comment]
Looks good here. Thanks!
