### ISSUE TITLE
[Linux] Firefox Gnome

### ISSUE THREAD

**Issue by MisteurTchaik** [NitruxSA/luv-icon-theme#164]
Would be nice to have an icon for Firefox web browser (for every DE btw). Attached is a screenshot for Gnome showing the missing icons in the applications view and application dock + desktop file.

![firefox](https://cloud.githubusercontent.com/assets/8634377/15448436/f88430f8-1f61-11e6-929c-2cfc953f72bd.png)

My .desktop file contains the following:
`Icon=firefox`

**Comment by UriHerrera** [comment]
I've added it for 64px and other sizes will follow.

Closing.
