### ISSUE TITLE
Lack of diversity within colour theme

### ISSUE THREAD

**Issue by V-Go** [NitruxSA/luv-icon-theme#166]
So I'm running Mint 18 Sarah ,as you can see the same theme seems to include different panel types, would it be possible to fix this issue?  (small icon colours)

![](http://i.imgur.com/Fc4BBqn.png)

**Comment by UriHerrera** [comment]
Sure. If the Mint devs would decide to use symbolic icons instead of normal icons in the software this wouldn't happen. This doesn't happen in other GTk software like that of Gnome.

Otherwise, I'd have to chaange those icons to not be monochrome.
